apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: content-deployment
spec:
  selector:
    matchLabels:
      app: content
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
      - name: catalog
        image: marianemuniz/catalog:v2
        ports:
        - containerPort: 8080
      hostNetwork: true
      dnsPolicy: Default

---

kind: Service
apiVersion: v1
metadata:
    name: content-service
spec: 
    selector: 
        app: catalog
    ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
    type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: sql-catalog
spec:
  ports:
  - port: 27017
    targetPort: 49763
---
kind: Endpoints
apiVersion: v1
metadata:
  name: sql-catalog
subsets:
  - addresses:
      - ip: 174.129.43.40
    ports:
      - port: 49763