apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: content-deployment
spec:
  selector:
    matchLabels:
      app: content
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: commerce
    spec:
      containers:
      - name: catalog
        image: marianemuniz/catalog:v1
        ports:
        - containerPort: 8080
      - name: content
        image: marianemuniz/content:v1
        ports:
        - containerPort: 8080
      - name: pricing
        image: marianemuniz/pricing:v1
        ports:
        - containerPort: 8080
      - name: stock
        image: marianemuniz/stock:v1
        ports:
        - containerPort: 8080
      hostNetwork: true
      dnsPolicy: Default

---

kind: Service
apiVersion: v1
metadata:
    name: content-service
spec: 
    selector: 
        app: catalog
    ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
    type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: external-catalog-sql
spec: 
  type: ExternalName 
  externalName: ec2-174-129-43-40.compute-1.amazonaws.com