apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: content-deployment
spec:
  selector:
    matchLabels:
      app: content
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
      - name: catalog
        image: marianemuniz/catalog:latest
        ports:
        - containerPort: 8080