server:
  port: 10001
spring:
  application:
    name: farm-catalog
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://192.168.0.50:3306/catalog?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: password
    initialization-mode: always
  activemq:
    broker-url: tcp://docker-server.com:61616?jms.redeliveryPolicy.maximumRedeliveries=1
    user: admin
    password: admin
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://configuration-server.com:8081/eureka
    register-with-eureka: true

app:
  protocol: "http://"

logging:
  file:
    max-history: 1
    max-size: 10MB
    name: /home/scott/Projects/logs/catalog.log
  pattern:
    level: DEBUG
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace